"""ti_sub_state

Revision ID: 128229b9b992
Revises: 1507a7289a2f
Create Date: 2017-11-01 12:34:08.409651

"""

# revision identifiers, used by Alembic.
revision = '128229b9b992'
down_revision = '1507a7289a2f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('task_fail')
    op.create_index('dr_run_id', 'dag_run', ['dag_id', 'run_id'], unique=True)
    op.drop_index('dag_id', table_name='dag_run')
    op.drop_index('dag_id_2', table_name='dag_run')
    op.drop_index('idx_job_state_heartbeat', table_name='job')
    op.add_column('task_instance', sa.Column('sub_state', sa.String(length=32), nullable=True))
    op.add_column('task_instance', sa.Column('sub_state_timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_task_instance_sub_state'), 'task_instance', ['sub_state'], unique=False)
    op.drop_index('dag_id', table_name='task_instance_timeout')
    op.drop_index('dagrun_run_id', table_name='task_instance_timeout')
    op.drop_column('users', 'password')
    op.alter_column('xcom', 'execution_date',
               existing_type=mysql.DATETIME(fsp=6),
               nullable=False)
    op.alter_column('xcom', 'timestamp',
               existing_type=mysql.DATETIME(fsp=6),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('xcom', 'timestamp',
               existing_type=mysql.DATETIME(fsp=6),
               nullable=True)
    op.alter_column('xcom', 'execution_date',
               existing_type=mysql.DATETIME(fsp=6),
               nullable=True)
    op.add_column('users', sa.Column('password', mysql.VARCHAR(collation=u'utf8mb4_bin', length=255), nullable=True))
    op.create_index('dagrun_run_id', 'task_instance_timeout', ['dagrun_run_id'], unique=True)
    op.create_index('dag_id', 'task_instance_timeout', ['dag_id', 'task_id', 'execution_date'], unique=True)
    op.drop_index(op.f('ix_task_instance_sub_state'), table_name='task_instance')
    op.drop_column('task_instance', 'sub_state_timestamp')
    op.drop_column('task_instance', 'sub_state')
    op.create_index('idx_job_state_heartbeat', 'job', ['state', 'latest_heartbeat'], unique=False)
    op.create_index('dag_id_2', 'dag_run', ['dag_id', 'run_id'], unique=True)
    op.create_index('dag_id', 'dag_run', ['dag_id', 'execution_date'], unique=True)
    op.drop_index('dr_run_id', table_name='dag_run')
    op.create_table('task_fail',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('task_id', mysql.VARCHAR(collation=u'utf8mb4_bin', length=250), nullable=False),
    sa.Column('dag_id', mysql.VARCHAR(collation=u'utf8mb4_bin', length=250), nullable=False),
    sa.Column('execution_date', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('start_date', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('end_date', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('duration', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate=u'utf8mb4_bin',
    mysql_default_charset=u'utf8mb4',
    mysql_engine=u'InnoDB'
    )
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('username', mysql.VARCHAR(collation=u'utf8mb4_bin', length=250), nullable=True),
    sa.Column('email', mysql.VARCHAR(collation=u'utf8mb4_bin', length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate=u'utf8mb4_bin',
    mysql_default_charset=u'utf8mb4',
    mysql_engine=u'InnoDB'
    )
    # ### end Alembic commands ###
